version: '3.8'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs # Ensure this path is correct
      - ./vhost.d:/etc/nginx/vhost.d # Added vhost.d mapping
    networks:
      - nginx-proxy
    restart: always

  your-app:
    build:
      context: .
      dockerfile: DockerFile
    environment:
      - VIRTUAL_HOST=slnnzmtl.xyz
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true