services:
  dev:
    container_name: slnnzmtl-xyz-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    environment:
      - VIRTUAL_HOST=localhost
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M