services:
  maintenance:
    container_name: slnnzmtl-xyz-maintenance
    build:
      context: ./maintenance
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=slnnzmtl.xyz
      - LETSENCRYPT_HOST=slnnzmtl.xyz
      - LETSENCRYPT_EMAIL=slonanezametil@example.com
    networks:
      - nginx-proxy
      - prod_network
    deploy:
      resources:
        limits:
          memory: 64M
        reservations:
          memory: 32M
    volumes:
      - ./certbot/conf:/etc/letsencrypt:ro

  prod:
    container_name: slnnzmtl-xyz-prod
    build:
      context: .
      dockerfile: Dockerfile
      target: production-stage
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=slnnzmtl.xyz
      - LETSENCRYPT_HOST=slnnzmtl.xyz
      - LETSENCRYPT_EMAIL=slonanezametil@example.com
    networks:
      - nginx-proxy
      - prod_network
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    volumes:
      - ./certbot/www:/var/www/certbot:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./nginx.prod.conf:/etc/nginx/conf.d/default.conf:ro

networks:
  nginx-proxy:
    external: true
  prod_network:
    name: prod_network 