FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache python3 make g++ git

RUN git clone --branch dev https://github.com/slnnzmtl/Vue-Personal-Portfolio.git .

RUN npm install

EXPOSE 5173

CMD ["npm", "run", "dev"]