services:
  # maintenance:
  #   container_name: slnnzmtl-xyz-maintenance
  #   build:
  #     context: ./maintenance
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:80"
  #   restart: unless-stopped
  #   environment:
  #     - VIRTUAL_HOST=slnnzmtl.xyz
  #   networks:
  #     - nginx-proxy
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 64M
  #       reservations:
  #         memory: 32M

  prod:
    container_name: slnnzmtl-xyz-prod
    build:
      context: .
      dockerfile: Dockerfile
      target: production-stage
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=slnnzmtl.xyz
    networks:
      - nginx-proxy
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

networks:
  nginx-proxy:
    external: true