services:
  dev:
    profiles: ["dev"]
    container_name: slnnzmtl-xyz-dev
    build:
      context: .
      dockerfile: Dockerfile
      target: build-stage
    ports:
      - "5173:5173"
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run dev
    environment:
      - NODE_ENV=development
      - VITE_HOST=0.0.0.0
    networks:
      - dev_network
    deploy:
      resources:
        limits:
          memory: 384M
        reservations:
          memory: 128M

  prod:
    container_name: slnnzmtl-xyz-prod
    build:
      context: .
      dockerfile: Dockerfile
      target: production-stage
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=slnnzmtl.xyz
      - LETSENCRYPT_HOST=slnnzmtl.xyz
      - LETSENCRYPT_EMAIL=slonanezametil@example.com
    networks:
      - nginx-proxy
      - prod_network
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

networks:
  dev_network:
    name: dev_network
  nginx-proxy:
    external: true
  prod_network:
    name: prod_network 