services:

  portfolio-service:
    container_name: portfolio-service
    build:
      context: .
      dockerfile: Dockerfile
      target: production-stage
    restart: unless-stopped
    networks:
      - nginx-proxy
    volumes:
      - ./nginx.prod.conf:/etc/nginx/nginx.conf
    environment:
      - VIRTUAL_HOST=slnnzmtl.xyz
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 10s
      timeout: 30s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 256M
    security_opt:
      - no-new-privileges:true

volumes:
  html:

networks:
  nginx-proxy:
    external: true