name: Deploy to VPS

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest # Use a GitHub-hosted runner

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4 

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.0 
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          port: ${{ secrets.VPS_PORT || 22 }} 
          script: |
            cd /root/containers/slnnzmtl-xyz # Assuming rebuild.sh is in the user's home directory
            
            ./rebuild.sh
            
            echo "Rebuild script execution finished on VPS."